version: '3.8'

services:
  home-app:
    build:
      context: ./Home
      dockerfile: Dockerfile
    ports:
      - "3331:3331"
    container_name: home_app

  customer-app:
    build:
      context: ./Customers
      dockerfile: Dockerfile
    ports:
      - "3332:3332"
    container_name: customer_app

  nginx:
    image: nginx:latest
    ports:
      - "5555:5555"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - home-app
      - customer-app

# nginx ka config yaha likh ke conatiner wale location pe change kar rahe